# site properties and page defaults
title: Applied Infectious Disease Dyanmcis 
subtitle: 
description: Decisions about public health response to an outbreak need to be made even when there is substantial uncertainty and unpredictability. Our group develops and applies mathematical and statistical
methods to quantify infectious disease dynamics to inform decision suport for public health and healthcare response to outbreak. Work from our group has has served as the backbone for the public health 
response to SARS-CoV-2 in Utah and other states and to Diphtheria outbreak responses across 2 continents. We are currently working to better understand how to reconstruct transmission and determine 
who-infected-whom healthcare associated pathogens, to improve the modeling toolkit for state and local public health agencies across the intermountain west to respond respiratory viruses, and to reduce 
transmission of epidemic Cholera through expanded treatment. 

Our group sits within the Infectious Disease Dyanmics group at the University of Utah in the Division of Epidemiology, within Department of Internal Medicine at the Spencer Fox Eccles School of Medicine.

header: images/CampusView.png
footer: images/background.jpg

# site social media and other links
links:
  email: lindsay.keegan@utah.edu
  website: https://www.utahinfectiousdiseasedynamics.org/
  github: Keeganlt
  twitter: Lindsay_Keegan

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
