- id: https://doi.org/10.1093/cid/ciz808
  type: paper
  image: https://academic.oup.com/view-large/figure/204930996/ciz808f0004.jpg
  repo: shauntruelove/Diphtheria

- id: https://doi.org/10.1038/s41597-022-01517-w
  type: paper
  image: https://www.nature.com/articles/s41597-022-01517-w/figures/1

- id: doi:10.1001/jamanetworkopen.2021.40906
  type: paper
  image: https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2787438#zld210279f1

- id: https://doi.org/10.3201/eid2705.203075
  type: paper
  image: https://wwwnc.cdc.gov/eid/article/27/5/20-3075-f3

- id: https://doi.org/10.1038/s41598-021-86811-0
  type: paper
  image: https://www.nature.com/articles/s41598-021-86811-0#Fig2

- id: doi:10.1001/jamanetworkopen.2021.0971
  type: paper
  image: https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2777439#zoi210048f2

- id: https://doi.org/10.1177/003335492098812
  type: paper
  image: https://journals.sagepub.com/doi/10.1177/0033354920988612#fig2-0033354920988612

- id: https://doi.org/10.7554/eLife.63009
  type: paper
  image: https://elifesciences.org/articles/63009#fig5

- id: https://doi.org/10.1016/j.vaccine.2020.06.081
  type: paper
  image: https://www.sciencedirect.com/science/article/pii/S0264410X20308847?via%3Dihub#f0005

- id: https://doi.org/10.1098/rstb.2018.0279
  type: paper
  image: https://royalsocietypublishing.org/doi/10.1098/rstb.2018.0279#RSTB20180279F3

- id: https://doi.org/10.1073/pnas.1714457115
  type: paper
  image: https://www.pnas.org/doi/full/10.1073/pnas.1714457115#fig04

- id: https://doi.org/10.1093/infdis/jix437
  type: paper
  image: https://academic.oup.com/view-large/figure/113026565/jix43702.jpeg

- id: https://doi.org/10.1016/j.jtbi.2016.01.022
  type: paper
  image: https://www.sciencedirect.com/science/article/pii/S0022519316000552?via%3Dihub#f0005

- id: https://doi.org/10.1007/s11538-014-9950-x
  type: paper
  image: https://link.springer.com/article/10.1007/s11538-014-9950-x#Fig4

- id: https://doi.org/10.1186/1471-2334-13-428
  type: paper
  image: https://bmcinfectdis.biomedcentral.com/articles/10.1186/1471-2334-13-428#Fig4
