- id: pmid:31425581
  image: images/Diphth.png
  repo: shauntruelove/Diphtheria

- id: doi:10.1101/2023.11.13.23298464
  type: paper
  image: images/Efm_copy.png

- id: doi:10.1093/aje/kwac201
  type: paper
  image: https://pubmed.ncbi.nlm.nih.gov/36396618/#&gid=article-figures&pid=figure-2-uid-1
